	USE master
	GO

	-- CRIANDO O BANCO DE DADOS DB_VENDAS
	CREATE DATABASE DB_VENDAS
	ON PRIMARY (NAME=N'DB_VENDAS', FILENAME=N'C:\Documentos\Projetos\Atos\02_SQLServer2019\Dados\DB_VENDAS.MDF')
	LOG ON (NAME=N'DB_VENDAS_LOG', FILENAME=N'C:\Documentos\Projetos\Atos\02_SQLServer2019\Dados\DB_VENDAS_LOG.LDF')
	GO

	-- MUDAMOS PARA O BANCO DB_VENDAS PARA INCLUIR SUAS TABELAS
	USE DB_VENDAS
	GO

	CREATE TABLE TB_CLIENTES
	(
		DOCUMENTO VARCHAR(14) NOT NULL,
		NOME VARCHAR(60) NOT NULL,
		TELEFONE VARCHAR(20) NOT NULL,
		EMAIL VARCHAR(100) NOT NULL,
		PRIMARY KEY(DOCUMENTO),
		CHECK(LEN(DOCUMENTO) = 11 OR LEN(DOCUMENTO) = 14)
	)
	GO

	CREATE TABLE TB_PEDIDOS
	(
		ID INT IDENTITY(1, 1) PRIMARY KEY,
		DOC_CLIENTE VARCHAR(14) NOT NULL,
		DATAPEDIDO DATETIME NOT NULL,
		NUMEROPEDIDO VARCHAR(20) NOT NULL,
		SITUACAO SMALLINT NOT NULL, --1: ABERTO, 2: FECHADO E N PAGO, 3: PAGO
		FOREIGN KEY(DOC_CLIENTE) REFERENCES TB_CLIENTES(DOCUMENTO),
		CHECK(SITUACAO >= 1 AND SITUACAO <= 3),
		UNIQUE(NUMEROPEDIDO)
	)
	GO


	CREATE TABLE TB_CATEGORIAS
	(
		ID INT IDENTITY(1, 1) PRIMARY KEY,
		DESCRICAO VARCHAR(50) NOT NULL
	)
	GO


	CREATE TABLE TB_PRODUTOS
	(
		ID INT IDENTITY(1, 1) PRIMARY KEY,
		ID_CATEGORIA INT NOT NULL,
		DESCRICAO VARCHAR(100) NOT NULL,
		UNIDADE VARCHAR(10) NOT NULL,
		PRECO_CUSTO FLOAT NOT NULL,
		FOREIGN KEY(ID_CATEGORIA) REFERENCES TB_CATEGORIAS(ID),
		CHECK(PRECO_CUSTO >= 0)
	)
	GO


	CREATE TABLE TB_ITENS
	(
		ID INT IDENTITY(1, 1) PRIMARY KEY,
		ID_PEDIDO INT NOT NULL,
		ID_PRODUTO INT NOT NULL,
		QUANTIDADE FLOAT NOT NULL,
		VALOR_TOTAL FLOAT NOT NULL,
		FOREIGN KEY(ID_PEDIDO) REFERENCES TB_PEDIDOS(ID),
		FOREIGN KEY(ID_PRODUTO) REFERENCES TB_PRODUTOS(ID)
	)
	GO


	CREATE TABLE TB_FORNECEDORES
	(
		DOCUMENTO VARCHAR(14) NOT NULL,
		NOME VARCHAR(60) NOT NULL,
		TELEFONE VARCHAR(20) NOT NULL,
		EMAIL VARCHAR(100) NOT NULL,
		PRIMARY KEY(DOCUMENTO),
		CHECK(LEN(DOCUMENTO) = 11 OR LEN(DOCUMENTO) = 14)
	)
	GO


	CREATE TABLE TB_PRODUTOS_FORNECEDORES
	(
		ID INT IDENTITY(1, 1) PRIMARY KEY,
		ID_PRODUTO INT NOT NULL,
		DOC_FORNECEDOR VARCHAR(14) NOT NULL,
		FOREIGN KEY(DOC_FORNECEDOR) REFERENCES TB_FORNECEDORES(DOCUMENTO),
		FOREIGN KEY(ID_PRODUTO) REFERENCES TB_PRODUTOS(ID)
	)
	GO


	CREATE TABLE TB_ESTOQUE
	(
		ID INT IDENTITY(1, 1) PRIMARY KEY,
		ID_PRODUTO INT NOT NULL,
		QUANTIDADE FLOAT NOT NULL,
		FOREIGN KEY(ID_PRODUTO) REFERENCES TB_PRODUTOS(ID),
		CHECK(QUANTIDADE >= 0)
	)
	GO


	CREATE TABLE TB_CARTOES
	(
		NUMEROCARTAO VARCHAR(16) NOT NULL,
		LIMITE FLOAT NOT NULL,
		DATA_VENCIMENTO DATETIME NOT NULL,
		PRIMARY KEY(NUMEROCARTAO),
		CHECK(LEN(NUMEROCARTAO) = 16)
	)
	GO


	CREATE TABLE TB_FATURAS
	(
		ID INT IDENTITY(1, 1) PRIMARY KEY,
		ID_PEDIDO INT NOT NULL,
		NUMEROCARTAO VARCHAR(16) NOT NULL,
		VALOR FLOAT NOT NULL,
		STATUS SMALLINT NOT NULL,	--1: PENDENTE, 2:PAGO
		FOREIGN KEY(ID_PEDIDO) REFERENCES TB_PEDIDOS(ID),
		FOREIGN KEY(NUMEROCARTAO) REFERENCES TB_CARTOES(NUMEROCARTAO),
		CHECK(STATUS = 1 OR STATUS = 2)
	)
	GO