USE DB_FORUM
GO

-- Consultas combinando os foruns e os usuários

--1. Buscando os foruns(TITULO, DESCRICAO) e seus usuários (NOME, EMAIL)
SELECT 
	FORUM.TITULO, 
	FORUM.DESCRICAO,
	USUARIO.NOME, 
	USUARIO.EMAIL
FROM
	FORUM, USUARIO, COMENTARIOS
WHERE 
	FORUM.ID = COMENTARIOS.IDFORUM AND USUARIO.ID = COMENTARIOS.IDUSUARIO
GO

--2. Buscando os foruns(TITULO, DESCRICAO) e seus usuários (NOME, EMAIL) usando 
--   ALIAS para as tabelas.
SELECT 
	F.TITULO, 
	F.DESCRICAO,
	U.NOME, 
	U.EMAIL
FROM
	FORUM F, USUARIO U, COMENTARIOS C
WHERE 
	F.ID = C.IDFORUM AND U.ID = C.IDUSUARIO
GO


--3. Buscando os foruns(TITULO, DESCRICAO) e seus usuários (NOME, EMAIL) usando 
--   ALIAS para as tabelas e para os campos.
SELECT 
	F.TITULO AS TITLE, 
	F.DESCRICAO AS DESCRIPTION,
	U.NOME AS NAME, 
	U.EMAIL AS EMAIL
FROM
	FORUM F, USUARIO U, COMENTARIOS C
WHERE 
	F.ID = C.IDFORUM AND U.ID = C.IDUSUARIO
GO
