USE DB_FORUM
GO

-- USANDO JOINS ENTRE USUARIO E COMENTARIOS (MESMO PROCEDIMENTO USADO NO SCRIPT ANTERIOR)
SELECT 
	U.NOME, 
	U.EMAIL, 
	C.COMENTARIO
FROM 
	COMENTARIOS C INNER JOIN USUARIO U
ON
	U.ID = C.IDUSUARIO


-- USANDO LEFT JOIN APLICADO À CONSULTA ANTERIOR (COLOCANDO USUARIO COMO TABELA ALVO)
SELECT 
	U.NOME, 
	U.EMAIL, 
	C.COMENTARIO
FROM 
	USUARIO U  LEFT JOIN COMENTARIOS C
ON
	U.ID = C.IDUSUARIO
