USE DB_VENDAS
GO

SELECT 
	DOC_CLIENTE, CONVERT(VARCHAR(10), DATAPEDIDO, 103) AS 'DATA PEDIDO' , NUMEROPEDIDO,
	
	CASE SITUACAO 
		WHEN 1 THEN 'PEDIDO ABERTO'
		WHEN 2 THEN 'PEDIDO FECHADO'
		WHEN 3 THEN 'PEDIDO PAGO'
		ELSE 'PEDIDO CANCELADO'
	END AS SITUACAO
FROM TB_PEDIDOS