USE DB_VENDAS
GO

/*
	Usando as tabelas TB_CLIENTES, TB_PEDIDOS, TB_ITENS E TB_PRODUTOS, apresentar
	- o documnto do cliente,
	- o nome do cliente, 
	- numero do pedido
	- a quantidade de itens adicionadas em cada pedido.
*/

SELECT
	C.DOCUMENTO, 
	C.NOME, 
	P.NUMEROPEDIDO,
	--PR.DESCRICAO,
	COUNT(PR.DESCRICAO) AS QTDE_ITENS, 
	SUM(IT.VALOR_TOTAL) TOTAL_PEDIDO
FROM
	TB_CLIENTES C, TB_PEDIDOS P, TB_PRODUTOS PR, TB_ITENS IT
WHERE
	C.DOCUMENTO = P.DOC_CLIENTE
	AND P.ID = IT.ID_PEDIDO
	AND PR.ID = IT.ID_PRODUTO
GROUP BY
	C.DOCUMENTO, C.NOME, P.NUMEROPEDIDO
	--, PR.DESCRICAO
--HAVING SUM(IT.VALOR_TOTAL) > 500
ORDER BY
	P.NUMEROPEDIDO

