USE DB_VENDAS
GO


SELECT * FROM TB_PRODUTOS

SELECT 
	ID_CATEGORIA AS CATEGORIA, 
	SUM(PRECO_CUSTO) AS TOTAL, 
	AVG(PRECO_CUSTO) AS MEDIA,
	MIN(PRECO_CUSTO) AS MINIMO,
	MAX(PRECO_CUSTO) AS MAXIMO,
	STDEV(PRECO_CUSTO) AS 'DESVIO PADRAO',
	COUNT(PRECO_CUSTO) AS QTDE 
FROM TB_PRODUTOS
GROUP BY ID_CATEGORIA