USE DB_VENDAS
GO

-- tabela temporaria
-- para o usuário atual: #TAB_PEDIDOS
-- para todos os usuários (acesso global): ##TAB_PEDIDOS

SELECT 
	C.DOCUMENTO, 
	C.NOME, 
	P.NUMEROPEDIDO,
	P.ID,
	SUM(IT.VALOR_TOTAL) AS TOTAL_PEDIDO
	INTO #TAB_PEDIDOS		
FROM
	TB_CLIENTES C, TB_PEDIDOS P, TB_ITENS IT
WHERE
	C.DOCUMENTO = P.DOC_CLIENTE
	AND P.ID = IT.ID_PEDIDO
GROUP BY
	C.DOCUMENTO, C.NOME, P.NUMEROPEDIDO, P.ID

-- CONSULTANDO DADOS DA TABELA TEMPORARIA
SELECT * FROM #TAB_PEDIDOS

-- APLICANDO AGRUPAMENTO NA TABELA TEMPORARIA
SELECT 
	DOCUMENTO, NOME, SUM(TOTAL_PEDIDO) AS TOTAL 
FROM 
	#TAB_PEDIDOS
GROUP BY
	DOCUMENTO, NOME

--DROP TABLE #TAB_PEDIDOS