USE DB_VENDAS
GO

CREATE VIEW VW_PEDIDOS
AS
SELECT 
	C.DOCUMENTO, 
	C.NOME, 
	P.NUMEROPEDIDO,
	P.ID,
	SUM(IT.VALOR_TOTAL) AS TOTAL_PEDIDO	
FROM
	TB_CLIENTES C, TB_PEDIDOS P, TB_ITENS IT
WHERE
	C.DOCUMENTO = P.DOC_CLIENTE
	AND P.ID = IT.ID_PEDIDO
GROUP BY
	C.DOCUMENTO, C.NOME, P.NUMEROPEDIDO, P.ID
GO

SELECT * FROM VW_PEDIDOS
SELECT DOCUMENTO, NOME, TOTAL_PEDIDO FROM VW_PEDIDOS