USE DB_VENDAS
GO

CREATE VIEW VW_CLIENTES
AS
SELECT DOCUMENTO, NOME, EMAIL, TELEFONE FROM TB_CLIENTES
GO

SELECT * FROM VW_CLIENTES

INSERT INTO VW_CLIENTES(DOCUMENTO, NOME, EMAIL, TELEFONE) 
VALUES ('12274588401', 'Antenor Saraiva', 'antenor@mail.com', '4925-8878')

