CREATE OR ALTER FUNCTION FN_CALCULAR_IMPOSTO(@valor FLOAT)
	RETURNS FLOAT
AS
BEGIN
	RETURN @valor * 0.18
END
GO

-- A execução da função criada pelo usuario requer o uso do schema
SELECT DBO.FN_CALCULAR_IMPOSTO(100)
SELECT 
	DESCRICAO, 
	PRECO_CUSTO, 
	DBO.FN_CALCULAR_IMPOSTO(PRECO_CUSTO) AS IMPOSTO
FROM TB_PRODUTOS
