USE DB_VENDAS
GO

CREATE OR ALTER FUNCTION FN_CONVERTER_REAIS(@valor FLOAT)
	RETURNS VARCHAR(20)
AS
BEGIN
	RETURN FORMAT(@valor, 'C', 'pt-br')	
END
GO

-- Executando a função
SELECT DBO.FN_CONVERTER_REAIS(1200)