USE DB_VENDAS
GO

CREATE OR ALTER FUNCTION FN_CALCULAR_TOTAL_CATEGORIA(@id_cat INT)
	RETURNS FLOAT
AS
BEGIN
	DECLARE @total FLOAT
	SELECT @total = SUM(PRECO_CUSTO) FROM TB_PRODUTOS WHERE ID_CATEGORIA = @id_cat
	RETURN @total
END
GO

-- Executando a função
SELECT 
	DESCRICAO, 
	ID_CATEGORIA, 
	PRECO_CUSTO, 
	DBO.FN_CALCULAR_TOTAL_CATEGORIA(ID_CATEGORIA) AS TOTAL_CATEGORIA
FROM TB_PRODUTOS