USE DB_VENDAS
GO

-- Função tabular (retorna uma tabela)
CREATE OR ALTER FUNCTION FN_CALCULAR_TOTAL_PEDIDOS()
	RETURNS	@TOTAL_PEDIDOS TABLE (	DOCUMENTO VARCHAR(14), 
									NOME VARCHAR(60),
									NUMEROPEDIDO VARCHAR(20),
									QUANTIDADE INT,
									TOTAL FLOAT)
AS
BEGIN
	INSERT INTO @TOTAL_PEDIDOS	
	SELECT
		C.DOCUMENTO, 
		C.NOME, 
		P.NUMEROPEDIDO,
		COUNT(PR.DESCRICAO) AS QTDE_ITENS, 
		SUM(IT.VALOR_TOTAL) TOTAL_PEDIDO
	FROM
		TB_CLIENTES C, TB_PEDIDOS P, TB_PRODUTOS PR, TB_ITENS IT
	WHERE
		C.DOCUMENTO = P.DOC_CLIENTE
		AND P.ID = IT.ID_PEDIDO
		AND PR.ID = IT.ID_PRODUTO
	GROUP BY
		C.DOCUMENTO, C.NOME, P.NUMEROPEDIDO
	RETURN
END
GO

-- Executando a função
SELECT * FROM DBO.FN_CALCULAR_TOTAL_PEDIDOS()