-- ARMAZENANDO SUBQUERY EM VARIÁVEL

DECLARE @sub TABLE(ID INT)
INSERT INTO @sub SELECT ID FROM TB_CATEGORIAS WHERE ID BETWEEN 2 AND 4

SELECT * FROM TB_PRODUTOS WHERE ID_CATEGORIA IN (SELECT * FROM @sub)
