USE DB_VENDAS
GO

CREATE OR ALTER TRIGGER TG_CLIENTES
	ON TB_CLIENTES
	AFTER INSERT, UPDATE, DELETE
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO TB_AUDIT_CLIENTE(DATA, DESCRICAO)
	SELECT GETDATE() AS DATA, I.NOME + ' INCLUIDO' AS DESCRICAO FROM INSERTED I
	UNION
	SELECT GETDATE() AS DATA, D.NOME + ' REMOVIDO' AS DESCRICAO FROM DELETED D

END
GO

