USE DB_VENDAS
GO

-- TRIGGER PARA NOTIFICAR A ATUALIZACAO DE PRECO DO PRODUTO
CREATE OR ALTER TRIGGER TG_PRODUTOS ON TB_PRODUTOS
	FOR UPDATE		-- OCORRE ANTES DA OPERACAO
AS 
BEGIN
	SET NOCOUNT ON;
	INSERT INTO TB_AUDIT_PRODUTO (ID_PRODUTO, DESCRICAO, VALOR_ANTIGO, VALOR_ATUAL)
	SELECT I.ID, I.DESCRICAO, D.PRECO_CUSTO, I.PRECO_CUSTO
	FROM INSERTED I JOIN DELETED D ON I.ID = D.ID
END
GO

-- Realizando uma alteração 
UPDATE TB_PRODUTOS SET PRECO_CUSTO = 3.5 WHERE ID = 4
SELECT * FROM TB_PRODUTOS
