CREATE OR ALTER VIEW vw_detalhes_cliente
AS
SELECT C.DOCUMENTO, C.NOME, C.TELEFONE, C.EMAIL, P.NUMEROPEDIDO
FROM TB_CLIENTES C JOIN TB_PEDIDOS P
ON C.DOCUMENTO = P.DOC_CLIENTE
GO

SELECT * FROM vw_detalhes_cliente
INSERT INTO vw_detalhes_cliente (DOCUMENTO, NOME, TELEFONE, EMAIL, NUMEROPEDIDO)
VALUES('47389875003','Abigail Costa','99874-3356','abigail@mail.com', '0008/2022')