USE DB_VENDAS
GO

CREATE OR ALTER TRIGGER TG_DETALHES_CLIENTE
	ON vw_detalhes_cliente INSTEAD OF INSERT
AS
BEGIN
	INSERT INTO TB_CLIENTES(DOCUMENTO, NOME, EMAIL, TELEFONE)
	SELECT I.DOCUMENTO, I.NOME, I.EMAIL, I.TELEFONE FROM INSERTED I
END
GO
